version: "3.9"

services:
  db:
    image: mysql:8
    container_name: kumeong-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kumeong_store
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/var/lib/mysql
      - ./kumeong_store.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    image: gegujin/kumeong-api:0.1.0
    container_name: kumeong-api
    restart: always
    environment:
      NODE_ENV: production
      DB_HOST: db            # ⬅ MySQL 컨테이너 이름
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: kumeong_store
    ports:
      - "3000:3000"
    depends_on:
      - db

  front:
    image: gegujin/kumeong-front:0.1.0
    container_name: kumeong-front
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - api
