apiVersion: apps/v1
kind: Deployment
metadata:
  name: kumeong-front
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: kumeong-front
  template:
    metadata:
      labels:
        app: kumeong-front
    spec:
      containers:
        - name: front
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.port }}
